version: '3.8'

services:
  db:
    image: mysql
    container_name: venture_audit_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - venture_audit_mysql_data:/var/lib/mysql

volumes:
  venture_audit_mysql_data:
